name: Build Dev

on:
  workflow_dispatch:
  push:
    branches:
      - 'dev'

jobs:
  build:
    runs-on: self-hosted
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: chmod +x ./gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        env:
          MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MOD_SNAPSHOT_BUILD: true
        run: ./gradlew build publish